//
//  LegacyKeyMigration.swift
//
//
//  Created for Keyfob – kf-gps
//

import Foundation
import NostrSDK

/// Migrates the legacy single-key ``KeyManager`` entry (`default.nsec`)
/// into a ``KeychainIdentityStore`` identity.
///
/// On first launch after the multi-identity upgrade, this utility:
/// 1. Checks if a legacy `default.nsec` key exists in the Keychain
/// 2. Reads the raw private key data
/// 3. Creates a new ``Identity`` in the ``KeychainIdentityStore``
///    with a copy of the key stored under `identity.<UUID>`
/// 4. Sets the migrated identity as active
/// 5. Optionally removes the legacy Keychain entry
/// 6. Records migration completion so it doesn't run again
///
/// ## Usage
///
/// Call ``migrateIfNeeded(to:removeLegacyEntry:)`` early in the app
/// lifecycle (e.g. in `AppDelegate` or first scene activation):
///
/// ```swift
/// let store = try KeychainIdentityStore()
/// try LegacyKeyMigration.migrateIfNeeded(to: store)
/// ```
///
/// The migration is idempotent — safe to call on every launch.
public enum LegacyKeyMigration {

    /// UserDefaults key tracking whether migration has completed.
    private static let migrationCompleteKey = "com.keyfob.legacyKeyMigration.complete"

    /// UserDefaults key storing the UUID of the migrated identity.
    private static let migratedIdentityIDKey = "com.keyfob.legacyKeyMigration.identityID"

    // MARK: - Public API

    /// Migrate the legacy `default.nsec` key to the identity store, if needed.
    ///
    /// This method is idempotent:
    /// - If migration was already completed, it returns immediately.
    /// - If no legacy key exists, it marks migration as complete (nothing to migrate).
    /// - If a legacy key exists and hasn't been migrated, it performs the migration.
    ///
    /// - Parameters:
    ///   - store: The ``KeychainIdentityStore`` to migrate into.
    ///   - removeLegacyEntry: Whether to delete the legacy `default.nsec`
    ///     Keychain entry after successful migration (default: `false`).
    ///     Keeping it provides rollback safety during the transition period.
    ///   - defaults: The `UserDefaults` for tracking migration state (default: `.standard`).
    /// - Returns: The migrated ``Identity``, or `nil` if no migration was needed.
    @discardableResult
    public static func migrateIfNeeded(
        to store: KeychainIdentityStore,
        removeLegacyEntry: Bool = false,
        defaults: UserDefaults = .standard
    ) throws -> Identity? {
        // Already migrated?
        if defaults.bool(forKey: migrationCompleteKey) {
            return nil
        }

        // Try to read the legacy key.
        guard let legacyKeyData = readLegacyKey() else {
            // No legacy key — mark as complete (nothing to migrate).
            defaults.set(true, forKey: migrationCompleteKey)
            return nil
        }

        // Derive the public key to check for duplicates.
        guard let privateKey = NostrSDK.PrivateKey(dataRepresentation: legacyKeyData),
              let sdkKeypair = NostrSDK.Keypair(privateKey: privateKey) else {
            // Key data is corrupt — mark as complete to avoid retrying.
            NSLog("[Keyfob][LegacyKeyMigration] Legacy key data is invalid, skipping migration.")
            defaults.set(true, forKey: migrationCompleteKey)
            return nil
        }

        // Check if this pubkey already exists in the store (e.g. user already
        // imported it manually or a previous partial migration occurred).
        let existing = try store.listIdentities()
        if let match = existing.first(where: { $0.pubkeyHex == sdkKeypair.publicKey.hex }) {
            // Already in store — ensure it's active and mark migration complete.
            if !match.isActive {
                try store.setActiveIdentity(match.id)
            }
            defaults.set(match.id.uuidString, forKey: migratedIdentityIDKey)
            defaults.set(true, forKey: migrationCompleteKey)
            return match
        }

        // Import the legacy key into the identity store.
        let identity = try store.importIdentity(
            privateKeyHex: privateKey.hex,
            source: .generated,  // It was generated by KeyManager originally
            label: "Default",
            makeActive: true
        )

        // Record migration state.
        defaults.set(identity.id.uuidString, forKey: migratedIdentityIDKey)
        defaults.set(true, forKey: migrationCompleteKey)

        // Optionally remove the legacy entry.
        if removeLegacyEntry {
            deleteLegacyKey()
        }

        NSLog("[Keyfob][LegacyKeyMigration] Migrated legacy key to identity \(identity.id) (pubkey: \(identity.pubkeyHex.prefix(8))...)")

        return identity
    }

    /// Check whether the legacy migration has been completed.
    public static func isMigrationComplete(defaults: UserDefaults = .standard) -> Bool {
        defaults.bool(forKey: migrationCompleteKey)
    }

    /// The UUID of the identity created during migration, if any.
    public static func migratedIdentityID(defaults: UserDefaults = .standard) -> UUID? {
        guard let str = defaults.string(forKey: migratedIdentityIDKey) else { return nil }
        return UUID(uuidString: str)
    }

    /// Reset migration state (for testing or re-migration scenarios).
    ///
    /// > Warning: This does not delete the migrated identity or restore the
    /// > legacy key. It only resets the migration-complete flag.
    public static func resetMigrationState(defaults: UserDefaults = .standard) {
        defaults.removeObject(forKey: migrationCompleteKey)
        defaults.removeObject(forKey: migratedIdentityIDKey)
    }

    // MARK: - Legacy Keychain Access

    /// Check whether a legacy `default.nsec` key exists in the Keychain.
    public static func hasLegacyKey() -> Bool {
        readLegacyKey() != nil
    }

    /// Read the raw private key data from the legacy `default.nsec` account.
    ///
    /// Returns `nil` if the key doesn't exist or Keychain access fails.
    /// Does NOT trigger biometric auth (uses a non-interactive query).
    static func readLegacyKey() -> Data? {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrAccount as String: KeychainConfig.legacyKeyAccount,
            kSecAttrService as String: KeychainConfig.service,
            kSecAttrAccessGroup as String: KeychainConfig.accessGroup,
            kSecMatchLimit as String: kSecMatchLimitOne,
            kSecReturnData as String: true,
            kSecUseDataProtectionKeychain as String: true,
            kSecAttrSynchronizable as String: kSecAttrSynchronizableAny
        ]

        var item: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &item)
        guard status == errSecSuccess, let data = item as? Data else {
            return nil
        }
        return data
    }

    /// Delete the legacy `default.nsec` Keychain entry.
    @discardableResult
    static func deleteLegacyKey() -> Bool {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrAccount as String: KeychainConfig.legacyKeyAccount,
            kSecAttrService as String: KeychainConfig.service,
            kSecAttrAccessGroup as String: KeychainConfig.accessGroup
        ]
        let status = SecItemDelete(query as CFDictionary)
        return status == errSecSuccess || status == errSecItemNotFound
    }
}
