//
//  NIP49Encryption.swift
//
//
//  Created for Keyfob – kf-q3r
//

import Foundation
import CryptoKit
import CryptoSwift
import Security

// MARK: - NIP49EncryptionError

/// Errors from NIP-49 ncryptsec encryption/decryption.
public enum NIP49EncryptionError: Error, Equatable {
    case invalidVersion(UInt8)
    case invalidPayloadLength(Int)
    case scryptDerivationFailed
    case encryptionFailed
    case decryptionFailed
    case invalidPrivateKeyLength(Int)
    case invalidPassword
}

// MARK: - KeySecurity

/// NIP-49 key security classification byte.
///
/// Indicates the known exposure level of the private key, informing
/// downstream consumers about the key's trustworthiness.
public enum KeySecurity: UInt8, Codable, Sendable {
    /// The private key has been known to have been handled insecurely
    /// (e.g., pasted in a browser, transmitted unencrypted).
    case unknown = 0x00
    /// The private key is believed to have NOT been handled insecurely.
    case known = 0x01
    /// The private key was generated by the client and has never been
    /// exposed outside of ncryptsec encrypted form.
    case generated = 0x02
}

// MARK: - NIP49Encryption

/// NIP-49 ncryptsec encryption and decryption.
///
/// Encrypts a 32-byte private key using a password-derived key (scrypt)
/// and XChaCha20-Poly1305 AEAD cipher.
///
/// ## Wire Format (from NIP-49)
/// ```
/// version (0x02) || log_n (1 byte) || salt (16 bytes) || nonce (24 bytes)
/// || key_security (1 byte) || encrypted_key (48 bytes = 32 + 16 MAC)
/// ```
///
/// Total payload: 91 bytes.
///
/// See [NIP-49](https://github.com/nostr-protocol/nips/blob/master/49.md).
public enum NIP49Encryption {

    /// Current NIP-49 version.
    public static let version: UInt8 = 0x02

    /// Total encrypted payload size: 1 + 1 + 16 + 24 + 1 + 48 = 91 bytes.
    public static let payloadLength = 91

    /// Default scrypt log₂(N) parameter. 2^16 = 65536 iterations.
    public static let defaultLogN: UInt8 = 16

    // MARK: - Encrypt

    /// Encrypt a 32-byte private key with a password.
    ///
    /// - Parameters:
    ///   - privateKeyBytes: The 32-byte private key to encrypt.
    ///   - password: The password to derive the encryption key from.
    ///   - logN: The scrypt log₂(N) parameter (default: 16).
    ///   - keySecurity: The key security classification.
    /// - Returns: The 91-byte encrypted payload.
    public static func encrypt(
        privateKeyBytes: Data,
        password: String,
        logN: UInt8 = defaultLogN,
        keySecurity: KeySecurity = .unknown
    ) throws -> Data {
        guard privateKeyBytes.count == 32 else {
            throw NIP49EncryptionError.invalidPrivateKeyLength(privateKeyBytes.count)
        }
        guard !password.isEmpty else {
            throw NIP49EncryptionError.invalidPassword
        }

        // Generate random salt and nonce.
        let salt = secureRandomBytes(count: 16)
        let nonce = secureRandomBytes(count: 24)

        // Derive encryption key via scrypt.
        let key = try deriveKey(password: password, salt: salt, logN: logN)

        // Encrypt with XChaCha20-Poly1305.
        let ciphertext = try xchacha20Poly1305Encrypt(
            key: key,
            nonce: nonce,
            plaintext: privateKeyBytes,
            aad: Data([keySecurity.rawValue])
        )

        // Assemble payload.
        var payload = Data(capacity: payloadLength)
        payload.append(version)
        payload.append(logN)
        payload.append(salt)    // 16 bytes
        payload.append(nonce)   // 24 bytes
        payload.append(keySecurity.rawValue)
        payload.append(ciphertext) // 48 bytes (32 encrypted + 16 tag)

        assert(payload.count == payloadLength)
        return payload
    }

    // MARK: - Decrypt

    /// Decrypt a 91-byte NIP-49 payload to recover the 32-byte private key.
    ///
    /// - Parameters:
    ///   - payload: The 91-byte encrypted payload.
    ///   - password: The password used during encryption.
    /// - Returns: A tuple of the decrypted 32-byte private key and key security byte.
    public static func decrypt(
        payload: Data,
        password: String
    ) throws -> (privateKey: Data, keySecurity: KeySecurity) {
        guard payload.count == payloadLength else {
            throw NIP49EncryptionError.invalidPayloadLength(payload.count)
        }
        guard !password.isEmpty else {
            throw NIP49EncryptionError.invalidPassword
        }

        // Parse header.
        let versionByte = payload[0]
        guard versionByte == version else {
            throw NIP49EncryptionError.invalidVersion(versionByte)
        }

        let logN = payload[1]
        let salt = payload[2..<18]       // 16 bytes
        let nonce = payload[18..<42]     // 24 bytes
        let keySecByte = payload[42]
        let ciphertext = payload[43..<91] // 48 bytes

        guard let keySecurity = KeySecurity(rawValue: keySecByte) else {
            throw NIP49EncryptionError.invalidVersion(keySecByte)
        }

        // Derive key via scrypt.
        let key = try deriveKey(password: password, salt: Data(salt), logN: logN)

        // Decrypt with XChaCha20-Poly1305.
        let plaintext = try xchacha20Poly1305Decrypt(
            key: key,
            nonce: Data(nonce),
            ciphertext: Data(ciphertext),
            aad: Data([keySecByte])
        )

        guard plaintext.count == 32 else {
            throw NIP49EncryptionError.decryptionFailed
        }

        return (plaintext, keySecurity)
    }

    // MARK: - scrypt Key Derivation

    /// Derive a 32-byte key from a password and salt using scrypt.
    static func deriveKey(password: String, salt: Data, logN: UInt8) throws -> Data {
        let passwordBytes = Array(password.utf8)
        let saltBytes = Array(salt)
        let n = 1 << Int(logN)

        do {
            let derived = try CryptoSwift.Scrypt(
                password: passwordBytes,
                salt: saltBytes,
                dkLen: 32,
                N: n,
                r: 8,
                p: 1
            ).calculate()
            return Data(derived)
        } catch {
            throw NIP49EncryptionError.scryptDerivationFailed
        }
    }

    // MARK: - XChaCha20-Poly1305

    /// Encrypt using XChaCha20-Poly1305.
    ///
    /// Implements the XChaCha20-Poly1305 construction:
    /// 1. Derive a subkey using HChaCha20(key, nonce[0:16])
    /// 2. Construct a 12-byte ChaCha nonce: 0x00000000 || nonce[16:24]
    /// 3. Use standard ChaCha20-Poly1305 with the subkey and 12-byte nonce
    static func xchacha20Poly1305Encrypt(
        key: Data,
        nonce: Data,
        plaintext: Data,
        aad: Data
    ) throws -> Data {
        // Step 1: Derive subkey via HChaCha20.
        let subkey = hchacha20(key: key, nonce: Data(nonce[nonce.startIndex..<nonce.startIndex + 16]))

        // Step 2: Build 12-byte nonce for ChaChaPoly.
        var chaChaNonce = Data(repeating: 0, count: 4)
        chaChaNonce.append(contentsOf: nonce[nonce.startIndex + 16..<nonce.startIndex + 24])

        // Step 3: Encrypt with CryptoKit's ChaChaPoly (ChaCha20-Poly1305).
        let symmetricKey = SymmetricKey(data: subkey)
        let chachaNonceObj = try ChaChaPoly.Nonce(data: chaChaNonce)
        let sealedBox = try ChaChaPoly.seal(
            plaintext,
            using: symmetricKey,
            nonce: chachaNonceObj,
            authenticating: aad
        )

        // Return ciphertext + tag (combined).
        return sealedBox.ciphertext + sealedBox.tag
    }

    /// Decrypt using XChaCha20-Poly1305.
    static func xchacha20Poly1305Decrypt(
        key: Data,
        nonce: Data,
        ciphertext: Data,
        aad: Data
    ) throws -> Data {
        guard ciphertext.count >= 16 else {
            throw NIP49EncryptionError.decryptionFailed
        }

        // Step 1: Derive subkey via HChaCha20.
        let subkey = hchacha20(key: key, nonce: Data(nonce[nonce.startIndex..<nonce.startIndex + 16]))

        // Step 2: Build 12-byte nonce.
        var chaChaNonce = Data(repeating: 0, count: 4)
        chaChaNonce.append(contentsOf: nonce[nonce.startIndex + 16..<nonce.startIndex + 24])

        // Step 3: Split ciphertext and tag.
        let tagStart = ciphertext.count - 16
        let ct = ciphertext[ciphertext.startIndex..<ciphertext.startIndex + tagStart]
        let tag = ciphertext[ciphertext.startIndex + tagStart..<ciphertext.endIndex]

        // Step 4: Decrypt with CryptoKit's ChaChaPoly.
        let symmetricKey = SymmetricKey(data: subkey)
        let chachaNonceObj = try ChaChaPoly.Nonce(data: chaChaNonce)
        let sealedBox = try ChaChaPoly.SealedBox(
            nonce: chachaNonceObj,
            ciphertext: Data(ct),
            tag: Data(tag)
        )

        do {
            return try ChaChaPoly.open(sealedBox, using: symmetricKey, authenticating: aad)
        } catch {
            throw NIP49EncryptionError.decryptionFailed
        }
    }

    // MARK: - HChaCha20

    /// HChaCha20: derive a 256-bit subkey from a 256-bit key and 128-bit nonce.
    ///
    /// This is the core of the XChaCha20 construction (RFC 8439 extension).
    /// Takes the first 16 bytes of a 24-byte nonce and produces a subkey.
    static func hchacha20(key: Data, nonce: Data) -> Data {
        // ChaCha20 constants: "expand 32-byte k"
        var state: [UInt32] = [
            0x61707865, 0x3320646e, 0x79622d32, 0x6b206574,  // constants
            0, 0, 0, 0,  // key[0..15]
            0, 0, 0, 0,  // key[16..31]
            0, 0, 0, 0   // nonce[0..15]
        ]

        // Load key bytes into state[4..11].
        for i in 0..<8 {
            state[4 + i] = key.withUnsafeBytes { ptr in
                ptr.load(fromByteOffset: i * 4, as: UInt32.self)
            }
        }

        // Load nonce bytes into state[12..15].
        for i in 0..<4 {
            state[12 + i] = nonce.withUnsafeBytes { ptr in
                ptr.load(fromByteOffset: i * 4, as: UInt32.self)
            }
        }

        // 20 rounds (10 double-rounds).
        for _ in 0..<10 {
            // Column rounds
            quarterRound(&state, 0, 4,  8, 12)
            quarterRound(&state, 1, 5,  9, 13)
            quarterRound(&state, 2, 6, 10, 14)
            quarterRound(&state, 3, 7, 11, 15)
            // Diagonal rounds
            quarterRound(&state, 0, 5, 10, 15)
            quarterRound(&state, 1, 6, 11, 12)
            quarterRound(&state, 2, 7,  8, 13)
            quarterRound(&state, 3, 4,  9, 14)
        }

        // HChaCha20 output: state[0..3] || state[12..15] (first and last 128 bits).
        var result = Data(count: 32)
        result.withUnsafeMutableBytes { ptr in
            for i in 0..<4 {
                ptr.storeBytes(of: state[i], toByteOffset: i * 4, as: UInt32.self)
            }
            for i in 0..<4 {
                ptr.storeBytes(of: state[12 + i], toByteOffset: (4 + i) * 4, as: UInt32.self)
            }
        }

        return result
    }

    /// ChaCha20 quarter round function.
    @inline(__always)
    private static func quarterRound(_ s: inout [UInt32], _ a: Int, _ b: Int, _ c: Int, _ d: Int) {
        s[a] = s[a] &+ s[b]; s[d] ^= s[a]; s[d] = (s[d] << 16) | (s[d] >> 16)
        s[c] = s[c] &+ s[d]; s[b] ^= s[c]; s[b] = (s[b] << 12) | (s[b] >> 20)
        s[a] = s[a] &+ s[b]; s[d] ^= s[a]; s[d] = (s[d] <<  8) | (s[d] >> 24)
        s[c] = s[c] &+ s[d]; s[b] ^= s[c]; s[b] = (s[b] <<  7) | (s[b] >> 25)
    }

    /// Generate cryptographically secure random bytes.
    private static func secureRandomBytes(count: Int) -> Data {
        var bytes = [UInt8](repeating: 0, count: count)
        let status = SecRandomCopyBytes(kSecRandomDefault, count, &bytes)
        precondition(status == errSecSuccess, "SecRandomCopyBytes failed with status \(status)")
        return Data(bytes)
    }
}
